spring:
  application:
    name: hystrix-client-service

server:
  port: 9502

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.service.host:localhost}:${eureka.service.port:9500}/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoint:
    env:
      post:
        enabled: true
    hystrix:
      stream:
        enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
    service-registry:
      enabled: true
    features:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"